openelisglobal/openelisglobal-core

app/src/us/mn/state/health/lims/result/action/util/ResultsLoadUtility.java

https://www.pivotaltracker.com/story/show/85804906

Significant digits got broken again

---

liquibase/OE5.1/MetaData.xml
liquibase/OE5.1/orphanTestCleanup.sql

https://www.pivotaltracker.com/story/show/84640384

Cleans up orphaned tests

---

app/WebContent/pages/result/resultListView.jsp
app/WebContent/pages/workplan/workplan.jsp

https://www.pivotaltracker.com/story/show/82251898

Fix bugs introduced by move test sections out of menus code.

---

liquibase/OE5.1/MetaData.xml

https://www.pivotaltracker.com/story/show/88753986

Kenya had been left out of assigning some modules to roles

---

liquibase/OE5.2/CDIRetroCIData.xml

https://www.pivotaltracker.com/story/show/79148748

Added new reflex tests for RetroCI

---

liquibase/OE5.1/KenyaData.xml
liquibase/OE5.1/testCatalogKenya/TestCatalogUpdate.xml

https://www.pivotaltracker.com/story/show/90851490

Fixed significant digits for urine gravity test

---

liquibase/OE5.1/testCatalogKenya/TestCatalogUpdate.xml

https://www.pivotaltracker.com/story/show/90938672

Updated the high normal range for Hepitis B/C viral load for Kenya

---

app/WebContent/pages/resultvalidation/resultValidation.jsp
app/src/us/mn/state/health/lims/resultvalidation/action/ResultValidationRetroCAction.java
app/src/us/mn/state/health/lims/workplan/action/ElisaAlgorithmWorkplanAction.java

https://www.pivotaltracker.com/story/show/91292520

Validation was broken for RetroCI

---

app/WebContent/pages/testConfiguration/testCatalog.jsp
app/src/us/mn/state/health/lims/testconfiguration/action/TestCatalogAction.java
app/src/us/mn/state/health/lims/testconfiguration/beans/TestCatalogBean.java

https://www.pivotaltracker.com/story/show/91460058

Bug fix and updated formating of test catalog

---

app/WebContent/pages/testConfiguration/testAdd.jsp

Result limits business rules done for numeric values

---

app/WebContent/pages/testConfiguration/testAdd.jsp
app/src/us/mn/state/health/lims/common/services/TypeOfTestResultService.java
app/src/us/mn/state/health/lims/common/util/StringUtil.java
app/src/us/mn/state/health/lims/testconfiguration/action/TestAddUpdate.java

Test add Result limits are now saved to db

---

app/WebContent/WEB-INF/struts-globalOpenELIS.xml
app/WebContent/pages/testConfiguration/testAdd.jsp
app/src/us/mn/state/health/lims/testconfiguration/action/TestAddAction.java

Interm checkin for testAdd story. changing to another story

---

app/WebContent/pages/sample/sampleAdd.jsp
app/src/us/mn/state/health/lims/common/provider/query/SampleEntryTestsForTypeProvider.java
app/src/us/mn/state/health/lims/panelitem/valueholder/PanelItem.java

https://www.pivotaltracker.com/story/show/93662684

Panels were not showing when adding sample types

---

liquibase/menus.xml

https://www.pivotaltracker.com/story/show/91460058

remove the confirmation order and report for CI and Kenya

---

app/src/MessageResources.properties
app/src/MessageResources_fr.properties
app/src/us/mn/state/health/lims/common/util/ConfigurationSideEffects.java
app/src/us/mn/state/health/lims/gender/daoimpl/GenderDAOImpl.java
app/src/us/mn/state/health/lims/menu/dao/MenuDAO.java
app/src/us/mn/state/health/lims/menu/daoimpl/MenuDAOImpl.java
app/src/us/mn/state/health/lims/menu/util/MenuUtil.java
app/src/us/mn/state/health/lims/menu/valueholder/Menu.hbm.xml
app/src/us/mn/state/health/lims/menu/valueholder/Menu.java
app/src/us/mn/state/health/lims/siteinformation/action/SiteInformationUpdateAction.java
liquibase/OE5.3/Base.xml
liquibase/OE5.3/MetaData.xml
liquibase/OE5.3/Schema.xml
liquibase/changeLogs.xml

https://www.pivotaltracker.com/story/show/92969810

Patient tab is a configurable item

---

installerTemplate/linux/setup_OpenELIS.py

https://www.pivotaltracker.com/story/show/93061718

Update installer to handle plugins

---

app/WebContent/pages/analyzerresults/analyzerResults.jsp
app/src/us/mn/state/health/lims/common/services/PluginAnalyzerService.java
app/src/us/mn/state/health/lims/plugin/PluginLoader.java

https://www.pivotaltracker.com/story/show/94120148

Added more catches for plugins

---

app/WebContent/css/openElisCore.css
app/src/us/mn/state/health/lims/result/action/util/ResultsLoadUtility.java
app/src/us/mn/state/health/lims/resultvalidation/util/ResultsValidationRetroCIUtility.java
app/src/us/mn/state/health/lims/testreflex/action/util/RetroCIReflexActions.java

https://www.pivotaltracker.com/story/show/94208508

Prevent user from editing calculated CD4 absolute count at RetroCI

---

app/WebContent/pages/referral/referralOut.jsp
app/src/MessageResources_fr.properties

https://www.pivotaltracker.com/story/show/94206900

Fixed localization on referral page

---

liquibase/OE5.2/CDIRetroCIData.xml

https://www.pivotaltracker.com/story/show/94204576

Invalid and Indetirminate removed as possible results for Vironostika

---

app/src/MessageResources.properties

https://www.pivotaltracker.com/story/show/94142666

Summary of All Tests text correction

---

liquibase/OE5.2/Base.xml
liquibase/OE5.2/CI_IPCIData.xml

https://www.pivotaltracker.com/story/show/94205622

Corrected module bieng assigned to the wrong role at IPCI

---

liquibase/OE5.2/CI_IPCIData.xml

https://www.pivotaltracker.com/story/show/94204714

Corrected localization

---

app/src/us/mn/state/health/lims/common/formfields/CI_RETROAdminFormFields.java
app/src/us/mn/state/health/lims/common/formfields/DefaultAdminFormFields.java

https://www.pivotaltracker.com/story/show/94876674

Added admin->analyzer test names to all configurations

---

app/WebContent/pages/patient/patientManagement.jsp
app/src/MessageResources.properties
app/src/MessageResources_fr.properties
app/src/SystemConfiguration.properties
app/src/us/mn/state/health/lims/common/provider/validation/DateValidationProvider.java
app/src/us/mn/state/health/lims/common/util/ConfigurationProperties.java
app/src/us/mn/state/health/lims/common/util/DateUtil.java
app/src/us/mn/state/health/lims/common/util/DefaultConfigurationProperties.java
app/src/us/mn/state/health/lims/patient/action/PatientManagementUpdateAction.java

https://www.pivotaltracker.com/story/show/94139000

Prevents ill formed birthdates from being saved

---

app/src/us/mn/state/health/lims/common/util/ConfigurationProperties.java
app/src/us/mn/state/health/lims/common/util/DateUtil.java
app/src/us/mn/state/health/lims/common/util/DefaultConfigurationProperties.java
app/src/us/mn/state/health/lims/common/util/StringUtil.java
app/test/us/mn/state/health/lims/common/util/DateUtilTest.java

https://www.pivotaltracker.com/story/show/94139000

More sanity checking when handling ambiguous dates

---

app/WebContent/pages/patient/patientManagement.jsp
liquibase/OE5.2/MetaData.xml

https://www.pivotaltracker.com/story/show/94139000

Liquibase code to clean miss formated entry dates

---

app/src/us/mn/state/health/lims/analyzerresults/action/AnalyzerResultsAction.java

https://www.pivotaltracker.com/story/show/95108644

AnalyzerResults results are rounded to the correct significant digits

---

app/src/us/mn/state/health/lims/common/util/DateUtil.java

bug found and fixed in DateUtil.getAgeInWeeks

---

liquibase/OE5.2/Base.xml
liquibase/OE5.2/HaitiLNSPData.xml

https://www.pivotaltracker.com/story/show/94900052

Make the culture des selles reflexs non-quantifiable

---

app/WebContent/pages/sample/sampleEdit.jsp

https://www.pivotaltracker.com/story/show/95286536

Modify order page did not allow saving

---

app/src/us/mn/state/health/lims/analyzerresults/action/AnalyzerResultsSaveAction.java

https://www.pivotaltracker.com/story/show/94339526

Fixed bug that crashed RetroCI analyzer results saving

---

app/WebContent/WEB-INF/struts-globalOpenELIS.xml
app/WebContent/pages/test/batchTestReassignment.jsp
app/src/MessageResources.properties
app/src/MessageResources_fr.properties
app/src/us/mn/state/health/lims/common/action/IActionConstants.java
app/src/us/mn/state/health/lims/test/action/BatchTestReassignmentUpdateAction.java
app/src/us/mn/state/health/lims/test/action/BatchTestStatusChangeBean.java

https://www.pivotaltracker.com/story/show/96227446

Batch reassign of tests.

---

app/src/us/mn/state/health/lims/common/util/DateUtil.java
app/src/us/mn/state/health/lims/patient/valueholder/Patient.java
app/test/us/mn/state/health/lims/common/util/DateUtilTest.java

https://www.pivotaltracker.com/story/show/96304064

Made date conversion more robust

---

app/WebContent/pages/testConfiguration/testSectionCreate.jsp

https://www.pivotaltracker.com/story/show/82324932

Fixed bug caused by ' in data.  Effected adding test unit

---

app/WebContent/pages/testConfiguration/testCatalog.jsp
app/src/MessageResources.properties
app/src/MessageResources_fr.properties

https://www.pivotaltracker.com/story/show/97249790

Localiztion of view test catalog

---

app/WebContent/pages/analyzertestname/analyzerTestName.jsp
app/src/us/mn/state/health/lims/analyzerimport/action/AnalyzerTestNameAction.java
app/src/us/mn/state/health/lims/analyzerimport/action/AnalyzerTestNameUpdateAction.java
app/src/us/mn/state/health/lims/analyzerimport/action/beans/NamedAnalyzerTestMapping.java
app/src/us/mn/state/health/lims/analyzerimport/analyzerreaders/AnalyzerLineInserter.java
app/src/us/mn/state/health/lims/analyzerimport/dao/AnalyzerTestMappingDAO.java
app/src/us/mn/state/health/lims/analyzerimport/daoimpl/AnalyzerTestMappingDAOImpl.java
app/src/us/mn/state/health/lims/analyzerimport/util/AnalyzerTestNameCache.java
app/src/us/mn/state/health/lims/analyzerresults/action/AnalyzerResultsAction.java
app/src/us/mn/state/health/lims/common/services/PluginAnalyzerService.java

https://www.pivotaltracker.com/story/show/97424892

Able to handle analyzer plugins with missing mapping

---

app/src/MessageResources.properties
app/src/MessageResources_fr.properties
app/src/us/mn/state/health/lims/analyzerimport/util/AnalyzerTestNameCache.java

https://www.pivotaltracker.com/story/show/97424892

Added localization for new analyzer plugin workflow

---

app/src/us/mn/state/health/lims/analyzerresults/action/AnalyzerResultsSaveAction.java
app/src/us/mn/state/health/lims/analyzerresults/action/beanitems/AnalyzerResultItem.java
app/src/us/mn/state/health/lims/common/paging/PagingBean.java

https://www.pivotaltracker.com/story/show/97585974

GSOD when saving analyzer tests

---

app/WebContent/pages/result/resultListView.jsp

https://www.pivotaltracker.com/story/show/97750620

Fix to handle test unit with ' in name

---

app/WebContent/pages/testConfiguration/testAdd.jsp

Finished navigation for add test page

---

app/WebContent/pages/testConfiguration/testAdd.jsp

Updated guide for add test page

---

app/WebContent/pages/testConfiguration/testAdd.jsp
app/src/MessageResources.properties
app/src/MessageResources_fr.properties

Updated localization for add test page

---

app/WebContent/WEB-INF/struts-globalOpenELIS.xml
app/WebContent/WEB-INF/tiles-globalOpenELIS.xml
app/WebContent/pages/testConfiguration/sampleTypeRename.jsp
app/WebContent/pages/testConfiguration/testManagement.jsp
app/WebContent/scripts/ajaxCalls.js
app/src/MessageResources.properties
app/src/MessageResources_fr.properties
app/src/us/mn/state/health/lims/common/provider/query/EntityNamesProvider.java
app/src/us/mn/state/health/lims/common/services/DisplayListService.java
app/src/us/mn/state/health/lims/testconfiguration/action/SampleTypeRenameAction.java
app/src/us/mn/state/health/lims/testconfiguration/action/SampleTypeRenameUpdate.java
app/src/us/mn/state/health/lims/typeofsample/valueholder/TypeOfSample.hbm.xml
app/src/us/mn/state/health/lims/typeofsample/valueholder/TypeOfSample.java
liquibase/OE5.3/Base.xml
liquibase/OE5.3/MetaData.xml
liquibase/OE5.3/Schema.xml
liquibase/OE5.3/sampleTypeLocalization.xml
liquibase/OE5.3/sampleTypeLocalizationFiles/ciIPCIsampleTypeLocalization.sql
liquibase/OE5.3/sampleTypeLocalizationFiles/ciLNSPsampleTypeLocalization.sql
liquibase/OE5.3/sampleTypeLocalizationFiles/ciRegionalsampleTypeLocalization.sql
liquibase/OE5.3/sampleTypeLocalizationFiles/haitiClinicalsampleTypeLocalization.sql
liquibase/OE5.3/sampleTypeLocalizationFiles/haitiLNSPsampleTypeLocalization.sql
liquibase/OE5.3/sampleTypeLocalizationFiles/kenyasampleTypeLocalization.sql
liquibase/OE5.3/sampleTypeLocalizationFiles/retroCIsampleTypeLocalization.sql

https://www.pivotaltracker.com/story/show/96604420

Allow user to correct the spelling of sample types

---

app/WebContent/pages/patient/CI/arvInitialStudy.jsp
app/WebContent/pages/patient/CI/rtnStudy.jsp
app/WebContent/pages/sample/quickEntry.jsp
app/WebContent/pages/sample/sampleOrder.jsp

https://www.pivotaltracker.com/story/show/98491268

Bug fix:  date format prompts were showing as null

---

liquibase/OE5.3/sampleTypeLocalizationFiles/ciRegionalsampleTypeLocalization.sql

https://www.pivotaltracker.com/story/show/121687209
Update french Serum to English in liquibase/OE5.3/sampleTypeLocalizationFiles/ciRegionalsampleTypeLocalization.sql

OE.5.3 installer update fix

---

liquibase/OE5.3/sampleTypeLocalizationFiles/ciLNSPsampleTypeLocalization.sql
liquibase/OE5.3/sampleTypeLocalizationFiles/ciRegionalsampleTypeLocalization.sql
liquibase/OE5.3/sampleTypeLocalizationFiles/haitiClinicalsampleTypeLocalization.sql

Test management: Accent problem

#134314129

---

liquibase/OE6.1.x/ci_regional/AdditionalAdd.xml

add access to virology unit

---

liquibase/OE6.1.x/ci_regional/Site_information.xml

Reverts openelisglobal/openelisglobal-core#696

Revert "accession prefix added in regional"

---

liquibase/OE6.1.x/ci_regional/Site_information.xml

Reverts openelisglobal/openelisglobal-core#700

Revert "OE 6.2 real final"

---

liquibase/OE6.1.x/ci_regional/Site_information.xml

Reverts openelisglobal/openelisglobal-core#697

Revert "OE 6.2 Final"

---

app/src/MessageResources.properties
app/src/MessageResources_fr.properties

Study functionality from RETROCI version added as a configurable item to the regional version
CSV export of routine testing added
Menu management added to the admin page
Dropdown for test management added to admin menu item
Unit of measure now user manageable
Optional smaller print patient report to make all text fit on one page
Improved localization

OE 6.2 Final

---

app/src/us/mn/state/health/lims/security/SecurityFilter.java

fix Content-Security-Policy preventing js from running when inline or calling the eval function

CSP disbling js fix

---

app/src/us/mn/state/health/lims/security/SecurityFilter.java
liquibase/OE7.1/Base.xml
liquibase/OE7.1/systemmodule.xml
liquibase/OE7.1/systemrolemodule.xml

Liquibase changes to add permissions for batch entry and barcode printing
Changing Content Security Policy to allow embedded pdfs in Chrome

Test fixes

---

app/WebContent/pages/patient/patientManagement.jsp

Redid some of my git repo to extract just this fix. Should have minimal impact on other functionality.

Required field fix

---

app/build/classes/MessageResources_fr.properties
app/src/MessageResources_fr.properties

menu label 8.1

---

app/build/classes/MessageResources_fr.properties
app/src/MessageResources_fr.properties

Etiquette - ok

---

liquibase/OE8.2/Menu.xml

A fix for 8.2 regarding ElectronicOrder

fix changeset id
